//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 資料庫專題.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class beveragestore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public beveragestore()
        {
            this.recommendeddrink = new HashSet<recommendeddrink>();
            this.tea = new HashSet<tea>();
            this.usergroup = new HashSet<usergroup>();
        }

        [DisplayName("店名")]
        [Required(ErrorMessage = "這個欄位不能為空!")]
        public string shopName { get; set; }

        [DisplayName("店家數")]
        [RegularExpression(@"^\d*$", ErrorMessage = "請輸入數字")]
        [Required(ErrorMessage = "這個欄位不能為空!")]
        public Nullable<int> shopTotal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<recommendeddrink> recommendeddrink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tea> tea { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usergroup> usergroup { get; set; }
    }
}
