//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 資料庫專題.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class brtuEntities : DbContext
    {
        public brtuEntities()
            : base("name=brtuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<beveragestore> beveragestore { get; set; }
        public virtual DbSet<recommendeddrink> recommendeddrink { get; set; }
        public virtual DbSet<tea> tea { get; set; }
        public virtual DbSet<usergroup> usergroup { get; set; }
    }
}
