//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 資料庫專題.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tea
    {
        public int TeaId { get; set; }

        [DisplayName("店名")]
        public string shopName { get; set; }

        [DisplayName("茶種")]
        [Required(ErrorMessage = "這個欄位不能為空!")]
        [RegularExpression(@"^[^\d]$", ErrorMessage = "請輸入中文或英文")]
        public string Variety { get; set; }

        [DisplayName("茶種價格(TWD)")]
        [Required(ErrorMessage = "這個欄位不能為空!")]
        [RegularExpression(@"^\d*$", ErrorMessage = "請輸入數字")]
        public Nullable<int> VarietyPrice { get; set; }
    
        public virtual beveragestore beveragestore { get; set; }
    }
}
